### ISSUE TITLE
请问, Dataset中的bag有做相机和雷达的同步吗

### ISSUE THREAD

**Issue by jxx315** [hku-mars/r3live#10]
港大的同学好，
         我下载了数据集中的hku_park_01.bag，  发现实际上相机在15hz，lidar在10hz,      时间戳是无法做到对齐的。  是否r3live对于多传感器时间同步方面没有硬性要求？   [非同步误差dt也一起做状态估计了？]([![2021-12-30 18-33-14 的屏幕截图](https://user-images.githubusercontent.com/16752718/147744244-4d639b07-dabb-4dac-bf83-48469c0136d3.png)]([url]([url]([url]([url](url))))))

**Comment by ziv-lin** [comment]
是的，我们的R3LIVE在线估计了相机和雷达-IMU的外参以及时差

**Comment by ziv-lin** [comment]
This issue is closed for no more updates.
Thanks~

**Comment by Rogers34** [comment]
您好，我可以问一下，这个时差和外参的处理是在代码的哪个位置吗？谢谢啦！
