### ISSUE TITLE
r3live_mapping crashes on my own data, sample data in the paper is ok.

### ISSUE THREAD

**Issue by brytsknguyen** [hku-mars/r3live#105]
Hi guys,

Thanks for the great work.

I can run r3live with your sample data without any problem.

I am trying to use r3live for a setup similar to yours, consisting of 1 rgb camera ([basler](https://www.baslerweb.com/en/products/cameras/area-scan-cameras/ace/aca1600-60gc/)) and 1 livox avia.
The system in use is a NUC running ubuntu 18.04 with ROS melodic, opencv 3.3.1 / 4.5.3

When I run it the node r3live-mapping can run for a few frames then crashes with the error:
```
================================================================================REQUIRED process [r3live_mapping-2] has died!
process has died [pid 19223, exit code -11, cmd /home/nuc/Libraries/r3live_ws/devel/lib/r3live/r3live_mapping __name:=r3live_mapping __log:=/home/nuc/.ros/log/4a09534e-f324-11ec-ac68-8038fbc082c1/r3live_mapping-2.log].
log file: /home/nuc/.ros/log/4a09534e-f324-11ec-ac68-8038fbc082c1/r3live_mapping-2*.log
Initiating shutdown!
================================================================================
```
The bag file can be downloaded from here:
https://drive.google.com/file/d/1jcVMpa-2AnbgbDLu61ALUYhNR2wwuIcS/view

The only change i made in the config yaml is the camera parameters like below. The calibration parameters are from kalibr tool

[report-imucam-..m300_21062022_9.pdf](https://github.com/hku-mars/r3live/files/8970191/report-imucam-.m300_21062022_9.pdf)

```
r3live_vio:
   image_width: 1600
   image_height: 1200
   camera_intrinsic:
      [1786.613933, 0.0, 750.353020,
       0.0, 1787.779541, 595.078266,
       0.0, 0.0, 1.0 ] 
   camera_dist_coeffs: [-0.041809, 0.136929, 0.000474, -0.000807, 0.000000]  #k1, k2, p1, p2, k3
   # Fine extrinsic value. form camera-LiDAR calibration.
   camera_ext_R:
         [ -0.00443849,-0.00925293, 0.99994734,
            0.99998707, 0.00244163, 0.00446126,
           -0.00248278, 0.99995421, 0.00924197 ]
   camera_ext_t: [0.05794244, 0.02363634, 0.04225306]
```

Could you please give it a try and let me know what's wrong?

Regards,

**Comment by FengYuQ** [comment]
how do you solve this problem，could you tell me？

**Comment by guojiabo** [comment]
请问你解决了吗？我也遇到了这个问题
