### ISSUE TITLE
运行后rviz正常，但是没有稠密重建的结果只有里程计在动。

### ISSUE THREAD

**Issue by xqh5201314** [hku-mars/r3live#120]
运行后rviz正常，但是没有稠密重建的结果只有里程计在动。
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/106581654/188432905-7d1a6e63-0b7e-4ea0-a0c9-e0d00d561ab5.png">

**Comment by komorebi0315** [comment]
您好，请问您解决问题了吗
