### ISSUE TITLE
编译没问题，但是运行时报错了，是什么原因呢？

### ISSUE THREAD

**Issue by XuHao9166** [hku-mars/r3live#127]
Thread_id [140399578437376] set CPU-0 affinity success.
Thread_id [140399553259264] set CPU-1 affinity success.
Thread_id [140399561651968] set CPU-2 affinity success.
Thread_id [140399544866560] set CPU-3 affinity success.
Thread_id [140399570044672] set CPU-4 affinity success.
Thread_id [140383393892096] set CPU-5 affinity success.
================================================================================REQUIRED process [r3live_mapping-2] has died!
process has died [pid 21245, exit code -11, cmd /home/xh/Downloads/r3live-master/devel/lib/r3live/r3live_mapping __name:=r3live_mapping __log:=/home/xh/.ros/log/f42d3cee-4b82-11ed-b4b4-185680cb6ddf/r3live_mapping-2.log].
log file: /home/xh/.ros/log/f42d3cee-4b82-11ed-b4b4-185680cb6ddf/r3live_mapping-2*.log
Initiating shutdown!
================================================================================
[rvizvisualisation-3] killing on exit
[r3live_mapping-2] killing on exit
[r3live_LiDAR_front_end-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by guojiabo** [comment]
请问你解决了吗？
