### ISSUE TITLE
Custom livox driver

### ISSUE THREAD

**Issue by aditdoshi333** [hku-mars/r3live#13]
Hello,

Thanks for sharing the code. I want to run r3live on my collected data using livox avia. In r2live you suggested using your custom livox driver (https://github.com/ziv-lin/livox_ros_driver_for_R2LIVE). Is it the same for r3live?

Thank you

**Comment by ziv-lin** [comment]
Yes, please see Section. 6 in our ReadMe.md

**Comment by aditdoshi333** [comment]
Sorry my bad. Thank you
