### ISSUE TITLE
MID70+ZED_Camera+ZED_IMU

### ISSUE THREAD

**Issue by 525753936** [hku-mars/r3live#134]
您好，港大团队，为了方便说明我就用中文啦。
  我在使用zed2相机和MID70运行R3live时，我将用标定工具标定的参数矩阵写入了config文件里，同时修改了lauch话题名称，建图时，lio部分是正常运行有点云的，但不知道为什么RGB_Map 是空数据，RVIZ显示了订阅的话题是对的。
以下我的改写的配置文件、launch文件和bag包，请您看下有没有解决这个问题的思路或者方法~非常感谢。
[链接: https://pan.baidu.com/s/1j3-p4OJVw9rx8L2UOKe9Vw?pwd=1234 提取码: 1234 ](url)

**Comment by 525753936** [comment]
![7cee3d3a0a9b5ebc4353adc513b447c](https://user-images.githubusercontent.com/99471863/198993122-d6037932-2a08-43cc-83d9-4e5a06488d2c.jpg)

**Comment by Fafa-DL** [comment]
请问解决了吗，同样camera无法处理

**Comment by 525753936** [comment]
> 请问解决了吗，同样camera无法处理
你试一下用他自己的相机标定参数运行，这样是可以运行，尚不清楚原因
