### ISSUE TITLE
RAM memory use and saved maps location.

### ISSUE THREAD

**Issue by FPSychotic** [hku-mars/r3live#136]
Hi, I can see that the RAM memory (16gb) increase the use until it is full after a few minutes. Is this a expected behaviour? Any option to save the cache in SSD disk to free the memory?

Other issue is if I save the map with S key, it will be deleted after I save again, is it possible save the map without overwrite, just adding a number in the end or any other workaround?

Thanks by share

**Comment by lugendary** [comment]
Hello, I also ran into the problem of full memory. Have you solved it later

**Comment by FPSychotic** [comment]
> 

No, just waiting a answer
