### ISSUE TITLE
Syncronization of LiDAR, IMU, Camera

### ISSUE THREAD

**Issue by farhad-dalirani** [hku-mars/r3live#146]
Hello, 

I am a little bit confused about the synchronization part. I have an LiDAR (Volydine-16), RGB camera and an IMU.
All of them connected to a PC and I use them via ROS. 

The Lidar is 10Hz, camera 32Hz and IMU has 400 Hz.

I) Synchronization Method

> Three of them should be synchronized, for example I should sub-sample ROS packages of the three of them in very close time stamps?
> **To be more specific:**
> Camera sampling time: 1s, 2s, 3s, ..., 100s
> LiDAR sampling time: 1s, 2s, 3s, ..., 100s
> IMU sampling time: 1s, 2s, 3s, ..., 100s

> Or  I should collect data for camera and LiDAR, and sub-sample IMU packages that are close to LiDAR and camera timestamps? 
> **To be more specific:**
> Camera sampling time: 1s, 5s, 10s, 15s, ..., 100s
> LiDAR sampling time: 7s, 14s, 21s, ..., 98s
> IMU sampling time: 1s, 5s, 7s, 10s, 14s, ..., 98s, 100s

II) Do I need to do the syncronization or the r3live does that?

It would be great if you could clarify it. Thanks.

**Comment by ManChrys** [comment]
Hello @farhad-dalirani ,

as they said r3live make time sync alone with an algorith.

issue #7 

> [ziv-lin](https://github.com/ziv-lin) commented [on Nov 11, 2021](https://github.com/hku-mars/r3live/issues/7#issuecomment-966065780)
For the camera sensor, we do not make any hardware synchronization between LiDAR and camera sensor, the time-offset between IMU (LiDAR built-in) and LiDAR is online estimated by our algorithm (both R2LIVE and our new work R3LIVE).
