### ISSUE TITLE
catkin_make  error

### ISSUE THREAD

**Issue by hewujunTDT** [hku-mars/r3live#15]
error: invalid initialization of reference of type ‘const cv::ParallelLoopBody&’ from expression of type ‘render_pts_in_voxels_mp(std::shared_ptr<Image_frame>&, std::unordered_set<std::shared_ptr<RGB_Voxel> >*, const double&)::<lambda(const cv::Range&)>’
                           { thread_render_pts_in_voxel(r.start, r.end, img_ptr, &g_voxel_for_render, obs_time); });

**Comment by ziv-lin** [comment]
Such errors are caused due to the lower OpenCV version (less than 3.3). Please see Section 3.4 in our ReadMe.md

**Comment by hewujunTDT** [comment]
> Such errors are caused due to the lower OpenCV version (less than 3.3). Please see Section 3.4 in our ReadMe.md

thanks

**Comment by ziv-lin** [comment]
This issue is closed for no more updates.
Thanks~
