### ISSUE TITLE
LiDAR-Camera Calibration

### ISSUE THREAD

**Issue by farhad-dalirani** [hku-mars/r3live#158]
In the config file, there are LiDAR Camera calibration parameters like this:
```
# Fine extrinsic value. form camera-LiDAR calibration.
   camera_ext_R:
         [-0.00113207, -0.0158688, 0.999873,
            -0.9999999,  -0.000486594, -0.00113994,
            0.000504622,  -0.999874,  -0.0158682]
   # camera_ext_t: [0.050166, 0.0474116, -0.0312415] 
   camera_ext_t: [0,0,0] 
```

Is this parameters from LiDAR to camera coordinate or from camera coordinate to LiDAR?

**Comment by farhad-dalirani** [comment]
According to my experiments, it is from Camera coordinate to LiDAR coordinate.

**Comment by PengKunPROO** [comment]
@farhad-dalirani from author‘s code，I think the ext is from imu to camera
