### ISSUE TITLE
The following problem occurs when compiling r3live

### ISSUE THREAD

**Issue by Ningningwang11** [hku-mars/r3live#159]
c++: error: unrecognized command line option ‘-msse2’
c++: error: unrecognized command line option ‘-msse3’
r3live/r3live/CMakeFiles/r3live_mapping.dir/build.make:75: recipe for target 'r3live/r3live/CMakeFiles/r3live_mapping.dir/src/r3live.cpp.o' failed
make[2]: *** [r3live/r3live/CMakeFiles/r3live_mapping.dir/src/r3live.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....

The machine I use is an Nvidia Jetson agx Xavier（ARMv8 Processor rev 0 (v8l) × 8 ），Ubuntu18.04，opencv3.4.16。After compiling R3live according to the steps, the following problems will occur. Please help to check the cause of the error

**Comment by 19915370507** [comment]
l have some proble
