### ISSUE TITLE
Calibration  between camera and lidar

### ISSUE THREAD

**Issue by farhad-dalirani** [hku-mars/r3live#168]
Hello,

I use r3live with velodyne lidar. I calibrate camera and the lidar and in my calibration toolbox, the calibration result is good.

However, when I run R3Live, there is around 5 degree misalignment between the lidar and camera. For one case, I did not change sensors and I recorded a rosbag for on minutes. It was interesting for me that there is around 5 degree error in mapping between lidar and camera.

Do you know what can be the source of the problem?

In the right side of the below room there is a red cone on the ground, as you an see because of several degree misalignment, the red color are projected off the cone. Also, in the middle of the room, there is a diamond shape frame with yellow boundary. As it can be seen, some parts of the yellow boundary are projected on the wall.

For more information about my setting please see this issue: https://github.com/hku-mars/r3live/issues/157

![Screenshot from 2023-03-10 12-56-53](https://user-images.githubusercontent.com/65308831/224389368-4851fe24-ff68-405b-8128-f27430eed09d.png)

**Comment by farhad-dalirani** [comment]
The problem was my calibration tool. It was not accurate. A highly accurate lidar-camera calibration should be used.

**Comment by esaumar** [comment]
Hi @farhad-dalirani, can you tell me what calibration tool you used to get a highly accurate transformation?

**Comment by farhad-dalirani** [comment]
@esaumar 
for livox: https://github.com/hku-mars/livox_camera_calib
for velodyne: https://github.com/AFEICHINA/extended_lidar_camera_calib

**Comment by esaumar** [comment]
Thanks @farhad-dalirani! One last question, have you tried calibrating the IMU/LiDAR vs Camera with this repo https://github.com/ethz-asl/kalibr ?

**Comment by farhad-dalirani** [comment]
@esaumar no, I have not. I used Velodyne LiDAR which does not have an internal IMU, I used an external IMU; however, I put it under the LiDAR and tried my best to align the axes of the two sensors by my hand. It worked for me.
