### ISSUE TITLE
Similar to issue #82, confusion about point clouds undistortion 

### ISSUE THREAD

**Issue by Neo-cyber-hubb** [hku-mars/r3live#175]
Hello！
I recently discovered a similar problem. The function ImuProcess::lic_point_cloud_undistort in IMU_Processing.cpp probalily has something wrong. It removes the distortion of points via the state which is got by IMU preintegration. The IMU preintegration should start from the state of last lidar scan. However, the state of lidar named "g_lio_state" is also updated in r3live_vio.cpp. So the initial state in the function ImuProcess::lic_point_cloud_undistort is the state of the closest image frame, not the state of last lidar scan. Here are some timestamps of state, the first IMU, and the first lidar point.
-------------------------------------------------
state time: 0.000000
first IMU time: 1627807316.703947
lidar begin time: 1627807316.699958
-------------------------------------------------
-------------------------------------------------
state time: 1627807316.799591
first IMU time: 1627807316.799979
lidar begin time: 1627807316.800593
-------------------------------------------------
VIO start
-------------------------------------------------
state time: 1627807316.956820
first IMU time: 1627807316.905014
lidar begin time: 1627807316.900438
-------------------------------------------------
-------------------------------------------------
state time: 1627807317.048209
first IMU time: 1627807317.004979
lidar begin time: 1627807317.000261
-------------------------------------------------
-------------------------------------------------
state time: 1627807317.170325
first IMU time: 1627807317.099949
lidar begin time: 1627807317.100105
-------------------------------------------------
-------------------------------------------------
state time: 1627807317.383647
first IMU time: 1627807317.300969
lidar begin time: 1627807317.300594
-------------------------------------------------

I'm just beginning my study about SLAM based on lidar, IMU and camera. So I'm not sure if I'm right. 
Looking forward to your reply!

**Comment by littlelittle-bo** [comment]
Hi, I have the same question as you. I would like to ask if your problem has been solved? @Neo-cyber-hubb
