### ISSUE TITLE
seems Eigen version problem

### ISSUE THREAD

**Issue by Marshall-Hu** [hku-mars/r3live#18]
i try Eigen 3.3.4 3.4 but get errors, one of lines 
  ‘ScalarBinaryOpTraits’ in namespace ‘Eigen’ does not name a template type
   using ReturnScalar = typename Eigen::ScalarBinaryOpTraits<

anyone get ideal about this？

**Comment by ziv-lin** [comment]
I can get any clue from the informations you provide, can you give me more detail?

**Comment by Marshall-Hu** [comment]
it caused by Eigen cant find Sophus, and i have finally succeed with reinstalling Sophus in the correct Path.
