### ISSUE TITLE
为什么这篇实现里没有使用MTK库而是全部自己实现的卡尔曼滤波呢

### ISSUE THREAD

**Issue by DingFeng9313** [hku-mars/r3live#185]
如题，我发现到你们实验室好多工作包括FAST-LIO都用的ikfom工具箱。请问为什么这篇实现里没有使用MTK库而是全部自己实现的卡尔曼滤波呢？是工具箱有bug或者计算不准确吗？

**Comment by tub-sgg** [comment]
他这个是简化版本的，代码中高斯牛顿只迭代一次，所以就用自己写的这的版本吧
