### ISSUE TITLE
The height error in mapping

### ISSUE THREAD

**Issue by OliverShaoPT** [hku-mars/r3live#19]
Hello @ziv-lin ,

Thanks for sharing your great works. The accuracy and detail of R3LIVE real-time mapping are impressive, but there are still some problems. I built R3LIVE according to the instructions and run "hkust_campus_seq_00.bag", the results I got are not consistent with the PCD file published on GitHub.
As shown in the following screenshot, the picture above is the result I got, the picture below is the PCD result published on GitHub. There exist obvious height error in my testing. In the test of FAST-LIO2, the problem of height error also appears.
Did I miss something?

![1](https://user-images.githubusercontent.com/37506826/148027636-5598307d-7324-4fb6-b6c1-8362742e138a.png)

![2](https://user-images.githubusercontent.com/37506826/148027662-2fe2d8f2-afa1-463c-92fd-94c9e811b7bc.png)

Best regards

**Comment by ziv-lin** [comment]
It is hard to say, in our environments, it can close the loops well by itself. The result might show very little difference due to the difference in both software and hardware environments. And,  in the sequence of HKUST_campus_00 (1.3 km) and HKUST_campuse_01 (1.5 km), the little drift (e.g., 0.001 deg) at the beginning might cause a large error at the last. 
For most of the existing slam systems, no one can guarantee that the result is the same at each time and at each computation platform.

**Comment by EloyAldao** [comment]
Hi:

Where are the PCD files available to download?
I only found the bag files.

Thanks

**Comment by ziv-lin** [comment]
Some of our result can be download in this repo: https://github.com/ziv-lin/r3live_preview

**Comment by EloyAldao** [comment]
Thanks!!

**Comment by OliverShaoPT** [comment]
> 

You're right. My notebook has only 16GB of memory, but I noticed that your computer has more than 60 GB of memory. I'll try a better computer later. And I also want to test the upper limit of R3LIVE accuracy by adding the IMU with higher accuracy, such as Xsens 680G. (As the built-in IMU of AVIA is BMI088.)
Again, thanks your great works.

**Comment by OliverShaoPT** [comment]
> 

I run the same rosbag in FAST-LIO2, it works fine, there is no obvious height error. (As shown in the following picture.)
![3](https://user-images.githubusercontent.com/37506826/148154201-9d15c4c2-2a15-4b93-8083-87b5f9ddd905.png)

I wonder what is the recommended hardware configuration for R3LIVE? Actually, at the last third of HKUST_campus_00 sequence, my physical memory has been used up, can we speculate that the main reason is the lack of physical memory?

![4](https://user-images.githubusercontent.com/37506826/148154937-9847287e-6267-4dd3-be93-ab2733cb2b98.png)

**Comment by ziv-lin** [comment]
It seems that you zoom with different scales, cause the drift in r3live to seem larger? In our testing environment, R3LIVE can stable closes the loop itself.

**Comment by ziv-lin** [comment]
It is hard to say,  is there any loss of message due to the lack of mem?

**Comment by ziv-lin** [comment]
Is R3LIVE can stable close the loop in other smaller bag?

**Comment by OliverShaoPT** [comment]
> It seems that you zoom with different scales, cause the drift in r3live to seem larger? In our testing environment, R3LIVE can stable closes the loop itself.

My bad, the history point cloud in ROS_rviz will disappear over time. Here is the correct PCD save by FAST_LIO2. The height error also exists, but still better than other SLAM works. 
![3_1](https://user-images.githubusercontent.com/37506826/148170368-8cb78d89-84ac-4820-b633-2a4dbb82e2c3.png)

![3_2](https://user-images.githubusercontent.com/37506826/148170416-a6529cdc-6365-4070-9e54-90de74c6febb.png)

**Comment by ziv-lin** [comment]
Both FAST-LIO2, R2LIVE/R3LIVE never expect you can close the loop by traveling up to 1.3 Km in all scenarios at all computation platforms. If you have the requirement to build a large map, implementing loop detection and closure is your choice.

Our paper put this as an example, by saying that we can close the loop itself (at least in our real word experiment, see our recorded video https://www.youtube.com/watch?v=j5fT8NE5fdg) without the aid of additional procedure (i.e., without the aid of loop closure). Aims to show that the drift in our proposed is very low, which demonstrates that our proposed method has good accuracy in localization. This does not contrary to the fact that all slam systems are drifting over time, compare to other slam systems, our proposed system drifts less.

**Comment by OliverShaoPT** [comment]
> It is hard to say, is there any loss of message due to the lack of mem?

I slow down the play rate of rosbag to 0.5. The delay between rosbag and R3LIVE terminal is gone, but it couldn't close the loop itself. I'll try running it on the server later.

![5](https://user-images.githubusercontent.com/37506826/148174488-cdb13316-5786-443c-8256-49db9e0ed731.png)

**Comment by OliverShaoPT** [comment]
> Both FAST-LIO2, R2LIVE/R3LIVE never expect you can close the loop by traveling up to 1.3 Km in all scenarios at all computation platforms. If you have the requirement to build a large map, implementing loop detection and closure is your choice.
> 
> Our paper put this as an example, by saying that we can close the loop itself (at least in our real word experiment, see our recorded video https://www.youtube.com/watch?v=j5fT8NE5fdg) without the aid of additional procedure (i.e., without the aid of loop closure). Aims to show that the drift in our proposed is very low, which demonstrates that our proposed method has good accuracy in localization. This does not contrary to the fact that all slam systems are drifting over time, compare to other slam systems, our proposed system drifts less.

I totally agree with you. Compare with other SLAM works, FAST-LIO2 and R3LIVE impress me a lot. I may try to combine the FAST-LIO2 or R3LIVE with global sensors that offer absolute measurements for eliminating drift, such as GPS.

**Comment by ziv-lin** [comment]
Yes, as pointed before, if you have the requirement to build a large map, implementing loop detection and closure is your choice, otherwise, fusing with other sensors for providing an absolute measurement.
