### ISSUE TITLE
Image input error

### ISSUE THREAD

**Issue by Leekh951** [hku-mars/r3live#190]
First, your system was a very good algorithm for us to use. I'd like to thank you.
The problem we are currently facing is that image input is not being carried out within r3live_mapping even with the correct image topic. 
The config parameter was all written normally according to our system, and the launch file was also written according to our topic name. (We use opencv 4.4.0)
Please check the attached image.
- Unlike your sensor system, we used the Livox mid 360 + realsense D435i. (or livox avia + D455)
- The image topic name is /camera/color/image_raw.
- The image resolution was performed using 1280 x 720 and 640 x 480, but none of them were input.

I want to get a solution to the above error and the sensor information and image resolution information you used.

![Screenshot from 2023-08-04 11-50-49](https://github.com/hku-mars/r3live/assets/108344959/9e1c21a7-6b6b-463f-9ed2-3c87d8a406b4)
![Screenshot from 2023-08-01 16-01-04](https://github.com/hku-mars/r3live/assets/108344959/b917f957-5830-45a6-a4a4-fea9a97429f5)
![Screenshot from 2023-07-30 17-42-11](https://github.com/hku-mars/r3live/assets/108344959/d03f07e5-8c22-424e-b1da-34011275ab7e)
![Screenshot from 2023-07-30 17-39-50](https://github.com/hku-mars/r3live/assets/108344959/822366bf-4f29-431c-8717-06fbad5d6b15)

**Comment by MattiasTancred** [comment]
Did you find the solution?
