### ISSUE TITLE
全局快门相机的选择

### ISSUE THREAD

**Issue by kxch928925819** [hku-mars/r3live#2]
希望能提供相机的配置信息，以及驱动程序！我目前在大陆无法取得avia，受力只有horizon，但是还是很惊喜，看到港大再次分享先进的技术！FAST-LIO已经开始做一些项目相关的测试，看到真彩，还是按耐不住想试试！谢谢！

**Comment by ziv-lin** [comment]
配置性息可以从我们的论文中查到，驱动程序这个请follow厂商的manual

**Comment by kxch928925819** [comment]
谢谢！这就去查！




------------------ 原始邮件 ------------------
发件人: ziv-lin ***@***.***&gt;
发送时间: 2021年9月17日 12:51
收件人: hku-mars/r3live ***@***.***&gt;
抄送: Weiguo Zhao ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[hku-mars/r3live] 全局快门相机的选择 (#2)





 
配置性息可以从我们的论文中查到，驱动程序这个请follow厂商的manual
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
