### ISSUE TITLE
Drifts even though it's not moving.

### ISSUE THREAD

**Issue by miharaka** [hku-mars/r3live#201]
I will get colored point cloud in not moving sensor. So I input custom IMU topic " all 0".
But , at the situation, r3live drifts.
What kind of information should I input into the IMU to have it mapped while not moving?
(I use Livox Mid-70 and realsense d455.)

![image](https://github.com/hku-mars/r3live/assets/130530425/c38a72a3-8be6-4166-8ee6-1980a36cf267)

**Comment by txt1108** [comment]
我也有，请问怎么解决的？
