### ISSUE TITLE
Documentation - camera_ext_R is rotated in config.yaml

### ISSUE THREAD

**Issue by Camilochiang** [hku-mars/r3live#21]
Hei zin!
Again amazing work. I have the impression that the camera_ext_R is rotated in your config.yaml compared with the output of the [recomended calibration method](https://github.com/Livox-SDK/livox_camera_lidar_calibration). When I try just replacing the matrix directly from the livox tool , r3live do not crash but is not able to map.

Please correct me if im wrong. If not, would be good to mentioned it somewhere.

Greetings!

**Comment by Marshall-Hu** [comment]
Using his tool  "livox_camera_calib"  to get the  calib_result_matrix needing Matrix Transpose.

**Comment by Camilochiang** [comment]
My bad. Thanks!
