### ISSUE TITLE
estimation of camera exposure time

### ISSUE THREAD

**Issue by yao-yating** [hku-mars/r3live#216]
The paper of R3live++ demostrated that it can estimate the camera exposure time online, but the method doesn't seem to mention how this camera exposure time is estimated. I'm really confused about how to estimate the exposure time in system state by iterated kalman filter, I’m wondering if you could tell me the principle of realizing this， any help form you would be greatly appreciated. 
Additionally， thank you for your amazing work!

**Comment by tub-sgg** [comment]
R3LIVE++  I think, is not released. so there is not such part like camera exposure estimation
