### ISSUE TITLE
process [r3live LiDAR front_end-1] has died!

### ISSUE THREAD

**Issue by ZHG169** [hku-mars/r3live#217]
When using r3live, how should I resolve the following error?
`process has died [pid 104356, exit code -11, cmd /home/zhg/R3live/devel/lib/r3live/r3live_LiDAR_front_end /livox/lidar:=/livox/lidar __name:=r3live_LiDAR_front_end __log:=/home/zhg/.ros/log/f6603b86-561d-11ef-b66a-816f287eb621/r3live_LiDAR_front_end-1.log].
log file: /home/zhg/.ros/log/f6603b86-561d-11ef-b66a-816f287eb621/r3live_LiDAR_front_end-1*.log
Initiating shutdown!`

I am using the Livox LiDAR simulation (livox_avia) and RealSense camera simulation(D435i) packages in Gazebo to simulate r3live.
How should I resolve this issue? Do I need to replace any packages, or is it possible that my .yaml file is not configured correctly?

Relevant configuration and plugin sources：
1. [Livox LiDAR simulation](https://github.com/fratopa/Mid360_simulation_plugin)
2. [RealSense camera simulation](https://github.com/IntelRealSense/realsense-ros-release)
3. Ubuntu 20.04
4. ROS-noetic

Execution process of r3live：
![Screenshot from 2024-08-09 16-26-01](https://github.com/user-attachments/assets/e765ae61-b639-4419-ab7d-7b2fa068617b)

**Comment by hasankiyani007** [comment]
Hey, were you able to solve this? I have the same issue, while attempting to replicate all data via a Simulink Simulation. Any help would be appreciated.

**Comment by guojiabo** [comment]
请问你解决了吗？我也遇到了这个问题

**Comment by ZHG169** [comment]
> 请问你解决了吗？我也遇到了这个问题
> 

我後來採用fast livo，但也是有遇到相似的問題，後來去翻了一下可能是opencv版本抓錯的問題造成崩潰，可以看一下這個【【FAST-LIVO】1.0  FAST-LIVO编译以及运行程序时崩溃的解决办法-哔哩哔哩】 https://b23.tv/qJbu4hg
希望能幫到你

**Comment by ZHG169** [comment]
> Hey, were you able to solve this? I have the same issue, while attempting to replicate all data via a Simulink Simulation. Any help would be appreciated.

Sorry for reply to so late! I've used fast_livo instead of r3live. I also have some problem like this when I use fast livo. 【【FAST-LIVO】1.0  FAST-LIVO编译以及运行程序时崩溃的解决办法-哔哩哔哩】 https://b23.tv/qJbu4hg This video maybe can help you. It maybe the process use this wrong opencv version cause it crashed.

**Comment by guojiabo** [comment]
ok thanks

ZHG169 ***@***.***> 于2025年8月11日周一 22:22写道：

**Comment by guojiabo** [comment]
ok thanks
