### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by viniciusvidal2** [hku-mars/r3live#23]
The follow error happens when playing a bag file from the dataset. RViz is shutdown with all the other nodes. It seems to be when the first image is received, but not much else is shown even in the log files. Sorry for my lack of expertise in more means of investigation.

I am using ROS Melodic, and I compiled the code with OpenCV 4.5.3. Compilation went well.

![error_r3live](https://user-images.githubusercontent.com/16919781/148091689-242d9953-812e-49cf-9e21-a165c7311eea.png)

**Comment by ziv-lin** [comment]
For reporting bugs and problems, please follow the instruction guide in our ReadMe.md. Attaching both your hardware and software environment if possible (printed by R3LIVE, see the following figure) will be a great help for me in locating your problems.
![envs](https://user-images.githubusercontent.com/9316645/148146323-2a1e95f9-6528-4032-a5e9-a5fc86572f47.png)

**Comment by ziv-lin** [comment]
From your case, with referring to issue https://github.com/hku-mars/r3live/issues/11 
I suggest you check if the OpenCV you use for compiling the codes matches exactly the openCV in your runtime environment. That is , the openCV version oriented by R3LIVE should as same as the version info printed in your terminal after types:
```
pkg-config --modversion opencv
```

**Comment by viniciusvidal2** [comment]
I am trully sorry, I didn't see this part in the Readme. I attach my hardware description, and as you can see, I am using Opencv version 4.5.3. I had to download and compile this version separetelly, since Ros Melodic used 3.2. 
![hard](https://user-images.githubusercontent.com/16919781/148244738-3c97d49f-8e4f-4f79-955e-98f8f323efa9.png)
From your following suggestion, the output of the command is the following:
`pkg-config --modversion opencv
3.2.0`
Do you have any suggestions in setting that too? Thank you.

**Comment by ziv-lin** [comment]
From your case, it seems that your OpenCV is complied with 4.5.3 but run with OpenCV version 3.2.0, can you keep them the same? This is very very important to launch R3LIVE correctly.

**Comment by viniciusvidal2** [comment]
Perfect, already did it and it is working, thank you for your help!

**Comment by zengkailiang** [comment]
> Perfect, already did it and it is working, thank you for your help!

  Can you tell me how you solved it ?  I'm in the same situation as you， my ros melodic used opencv3.2.   I compiled the code with opencv4.4.0.

**Comment by viniciusvidal2** [comment]
You might do this checking to see which version is found when running the code in command prompt:

`pkg-config --modversion opencv4`

This page might be helpful to double check your installation procedure:

`https://linuxize.com/post/how-to-install-opencv-on-ubuntu-18-04/`

As a final advice, from the time I was struggling untill now, I found further issues with other libraries that you might be willing to use too, such as open3D, related to cmake version, for instance. My best advice in the end is to upgrade to Ubuntu 20, since it has a stable upgraded environment in general. **Cons**: don't do it if you have more than one machine using Ubuntu 18 and ROS Melodic, because ROS will face issues regarding Melodic and Noetic communications.
