### ISSUE TITLE
是否支持外置IMU

### ISSUE THREAD

**Issue by PeterJaq** [hku-mars/r3live#24]
目前尝试使用mid70+外置imu的配置方式，代码可以跑通，但是由于imu和lidar外参不同步效果并不好
请问如何可以完成imu外参配置?

**Comment by ziv-lin** [comment]
现阶段不支持，不过你可以修改相关的源代码以适配你的sensor setup。

**Comment by vipelz** [comment]
Will there be instructions in English to try R3live with a mid70 and an external Imu like the BOSCH BMI088?  thank you

**Comment by PeterJaq** [comment]
> 现阶段不支持，不过你可以修改相关的源代码以适配你的sensor setup。

Thank you!
