### ISSUE TITLE
Spinning LIDAR texture misalignment

### ISSUE THREAD

**Issue by AFEICHINA** [hku-mars/r3live#25]
Hi
      Thanks for your outstanding work and open source it.
      I modified the project and adapted it for spinning lidar. The results are shown in the figure:
![image](https://user-images.githubusercontent.com/26079089/148206869-5dbdd233-dcf8-4385-a995-ffe5cec4a221.png). I found the result is misalignment. The external parameter from my camera to IMU is set to rough external value and estimate_Intrinsic is set to 1. Do you have any other suggestions besides recalibrating the accurate initial value? thank you very much!

**Comment by ziv-lin** [comment]
For the calibration of LiDAR and Camera, I recommend you to use this repo: https://github.com/hku-mars/livox_camera_calib
