### ISSUE TITLE
LZ4_STREAMSIZE_U64

### ISSUE THREAD

**Issue by kxch928925819** [hku-mars/r3live#26]
In file included from /usr/include/flann/util/serialization.h:9:0,
                 from /usr/include/flann/util/matrix.h:35,
                 from /usr/include/flann/flann.hpp:41,
                 from /usr/include/pcl-1.8/pcl/kdtree/flann.h:50,
                 from /usr/include/pcl-1.8/pcl/kdtree/kdtree_flann.h:45,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/loam/IMU_Processing.hpp:19,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/loam/IMU_Processing.cpp:1:
/usr/include/flann/ext/lz4.h:196:57: error: conflicting declaration ‘typedef struct LZ4_stream_t LZ4_stream_t’
 typedef struct { long long table[LZ4_STREAMSIZE_U64]; } LZ4_stream_t;
                                                         ^~~~~~~~~~~~
In file included from /opt/ros/melodic/include/roslz4/lz4s.h:38:0,
                 from /opt/ros/melodic/include/rosbag/stream.h:46,
                 from /opt/ros/melodic/include/rosbag/chunked_file.h:46,
                 from /opt/ros/melodic/include/rosbag/bag.h:41,
                 from /home/dji/catkin_ws/src/r3live/r3live/./src/loam/include/common_lib.h:13,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/loam/IMU_Processing.hpp:12,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/loam/IMU_Processing.cpp:1:
/usr/include/lz4.h:196:57: note: previous declaration as ‘typedef struct LZ4_stream_t LZ4_stream_t’
 typedef struct { long long table[LZ4_STREAMSIZE_U64]; } LZ4_stream_t;
                                                         ^~~~~~~~~~~~
In file included from /usr/include/flann/util/serialization.h:9:0,
                 from /usr/include/flann/util/matrix.h:35,
                 from /usr/include/flann/flann.hpp:41,
                 from /usr/include/pcl-1.8/pcl/kdtree/flann.h:50,
                 from /usr/include/pcl-1.8/pcl/kdtree/kdtree_flann.h:45,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/loam/IMU_Processing.hpp:19,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/loam/IMU_Processing.cpp:1:
/usr/include/flann/ext/lz4.h:249:72: error: conflicting declaration ‘typedef struct LZ4_streamDecode_t LZ4_streamDecode_t’
 typedef struct { unsigned long long table[LZ4_STREAMDECODESIZE_U64]; } LZ4_streamDecode_t;
                                                                        ^~~~~~~~~~~~~~~~~~
In file included from /opt/ros/melodic/include/roslz4/lz4s.h:38:0,
                 from /opt/ros/melodic/include/rosbag/stream.h:46,
                 from /opt/ros/melodic/include/rosbag/chunked_file.h:46,
                 from /opt/ros/melodic/include/rosbag/bag.h:41,
                 from /home/dji/catkin_ws/src/r3live/r3live/./src/loam/include/common_lib.h:13,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/loam/IMU_Processing.hpp:12,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/loam/IMU_Processing.cpp:1:
/usr/include/lz4.h:249:72: note: previous declaration as ‘typedef struct LZ4_streamDecode_t LZ4_streamDecode_t’
 typedef struct { unsigned long long table[LZ4_STREAMDECODESIZE_U64]; } LZ4_streamDecode_t;
                                                                        ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/flann/util/serialization.h:9:0,
                 from /usr/include/flann/util/matrix.h:35,
                 from /usr/include/flann/flann.hpp:41,
                 from /usr/include/pcl-1.8/pcl/kdtree/flann.h:50,
                 from /usr/include/pcl-1.8/pcl/kdtree/kdtree_flann.h:45,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live.cpp:69:
/usr/include/flann/ext/lz4.h:196:57: error: conflicting declaration ‘typedef struct LZ4_stream_t LZ4_stream_t’
 typedef struct { long long table[LZ4_STREAMSIZE_U64]; } LZ4_stream_t;
                                                         ^~~~~~~~~~~~
In file included from /opt/ros/melodic/include/roslz4/lz4s.h:38:0,
                 from /opt/ros/melodic/include/rosbag/stream.h:46,
                 from /opt/ros/melodic/include/rosbag/chunked_file.h:46,
                 from /opt/ros/melodic/include/rosbag/bag.h:41,
                 from /home/dji/catkin_ws/src/r3live/r3live/./src/loam/include/common_lib.h:13,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live.cpp:59:
/usr/include/lz4.h:196:57: note: previous declaration as ‘typedef struct LZ4_stream_t LZ4_stream_t’
 typedef struct { long long table[LZ4_STREAMSIZE_U64]; } LZ4_stream_t;
                                                         ^~~~~~~~~~~~
In file included from /usr/include/flann/util/serialization.h:9:0,
                 from /usr/include/flann/util/matrix.h:35,
                 from /usr/include/flann/flann.hpp:41,
                 from /usr/include/pcl-1.8/pcl/kdtree/flann.h:50,
                 from /usr/include/pcl-1.8/pcl/kdtree/kdtree_flann.h:45,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live.cpp:69:
/usr/include/flann/ext/lz4.h:249:72: error: conflicting declaration ‘typedef struct LZ4_streamDecode_t LZ4_streamDecode_t’
 typedef struct { unsigned long long table[LZ4_STREAMDECODESIZE_U64]; } LZ4_streamDecode_t;
                                                                        ^~~~~~~~~~~~~~~~~~
In file included from /opt/ros/melodic/include/roslz4/lz4s.h:38:0,
                 from /opt/ros/melodic/include/rosbag/stream.h:46,
                 from /opt/ros/melodic/include/rosbag/chunked_file.h:46,
                 from /opt/ros/melodic/include/rosbag/bag.h:41,
                 from /home/dji/catkin_ws/src/r3live/r3live/./src/loam/include/common_lib.h:13,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live.cpp:59:
/usr/include/lz4.h:249:72: note: previous declaration as ‘typedef struct LZ4_streamDecode_t LZ4_streamDecode_t’
 typedef struct { unsigned long long table[LZ4_STREAMDECODESIZE_U64]; } LZ4_streamDecode_t;
                                                                        ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/flann/util/serialization.h:9:0,
                 from /usr/include/flann/util/matrix.h:35,
                 from /usr/include/flann/flann.hpp:41,
                 from /usr/include/pcl-1.8/pcl/kdtree/flann.h:50,
                 from /usr/include/pcl-1.8/pcl/kdtree/kdtree_flann.h:45,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live.hpp:70,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live_vio.cpp:48:
/usr/include/flann/ext/lz4.h:196:57: error: conflicting declaration ‘typedef struct LZ4_stream_t LZ4_stream_t’
 typedef struct { long long table[LZ4_STREAMSIZE_U64]; } LZ4_stream_t;
                                                         ^~~~~~~~~~~~
In file included from /opt/ros/melodic/include/roslz4/lz4s.h:38:0,
                 from /opt/ros/melodic/include/rosbag/stream.h:46,
                 from /opt/ros/melodic/include/rosbag/chunked_file.h:46,
                 from /opt/ros/melodic/include/rosbag/bag.h:41,
                 from /home/dji/catkin_ws/src/r3live/r3live/./src/loam/include/common_lib.h:13,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live.hpp:60,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live_vio.cpp:48:
/usr/include/lz4.h:196:57: note: previous declaration as ‘typedef struct LZ4_stream_t LZ4_stream_t’
 typedef struct { long long table[LZ4_STREAMSIZE_U64]; } LZ4_stream_t;
                                                         ^~~~~~~~~~~~
In file included from /usr/include/flann/util/serialization.h:9:0,
                 from /usr/include/flann/util/matrix.h:35,
                 from /usr/include/flann/flann.hpp:41,
                 from /usr/include/pcl-1.8/pcl/kdtree/flann.h:50,
                 from /usr/include/pcl-1.8/pcl/kdtree/kdtree_flann.h:45,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live.hpp:70,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live_vio.cpp:48:
/usr/include/flann/ext/lz4.h:249:72: error: conflicting declaration ‘typedef struct LZ4_streamDecode_t LZ4_streamDecode_t’
 typedef struct { unsigned long long table[LZ4_STREAMDECODESIZE_U64]; } LZ4_streamDecode_t;
                                                                        ^~~~~~~~~~~~~~~~~~
In file included from /opt/ros/melodic/include/roslz4/lz4s.h:38:0,
                 from /opt/ros/melodic/include/rosbag/stream.h:46,
                 from /opt/ros/melodic/include/rosbag/chunked_file.h:46,
                 from /opt/ros/melodic/include/rosbag/bag.h:41,
                 from /home/dji/catkin_ws/src/r3live/r3live/./src/loam/include/common_lib.h:13,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live.hpp:60,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live_vio.cpp:48:
/usr/include/lz4.h:249:72: note: previous declaration as ‘typedef struct LZ4_streamDecode_t LZ4_streamDecode_t’
 typedef struct { unsigned long long table[LZ4_STREAMDECODESIZE_U64]; } LZ4_streamDecode_t;
                                                                        ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/flann/util/serialization.h:9:0,
                 from /usr/include/flann/util/matrix.h:35,
                 from /usr/include/flann/flann.hpp:41,
                 from /usr/include/pcl-1.8/pcl/kdtree/flann.h:50,
                 from /usr/include/pcl-1.8/pcl/kdtree/kdtree_flann.h:45,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live.hpp:70,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live_lio.cpp:48:
/usr/include/flann/ext/lz4.h:196:57: error: conflicting declaration ‘typedef struct LZ4_stream_t LZ4_stream_t’
 typedef struct { long long table[LZ4_STREAMSIZE_U64]; } LZ4_stream_t;
                                                         ^~~~~~~~~~~~
In file included from /opt/ros/melodic/include/roslz4/lz4s.h:38:0,
                 from /opt/ros/melodic/include/rosbag/stream.h:46,
                 from /opt/ros/melodic/include/rosbag/chunked_file.h:46,
                 from /opt/ros/melodic/include/rosbag/bag.h:41,
                 from /home/dji/catkin_ws/src/r3live/r3live/./src/loam/include/common_lib.h:13,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live.hpp:60,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live_lio.cpp:48:
/usr/include/lz4.h:196:57: note: previous declaration as ‘typedef struct LZ4_stream_t LZ4_stream_t’
 typedef struct { long long table[LZ4_STREAMSIZE_U64]; } LZ4_stream_t;
                                                         ^~~~~~~~~~~~
In file included from /usr/include/flann/util/serialization.h:9:0,
                 from /usr/include/flann/util/matrix.h:35,
                 from /usr/include/flann/flann.hpp:41,
                 from /usr/include/pcl-1.8/pcl/kdtree/flann.h:50,
                 from /usr/include/pcl-1.8/pcl/kdtree/kdtree_flann.h:45,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live.hpp:70,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live_lio.cpp:48:
/usr/include/flann/ext/lz4.h:249:72: error: conflicting declaration ‘typedef struct LZ4_streamDecode_t LZ4_streamDecode_t’
 typedef struct { unsigned long long table[LZ4_STREAMDECODESIZE_U64]; } LZ4_streamDecode_t;
                                                                        ^~~~~~~~~~~~~~~~~~
In file included from /opt/ros/melodic/include/roslz4/lz4s.h:38:0,
                 from /opt/ros/melodic/include/rosbag/stream.h:46,
                 from /opt/ros/melodic/include/rosbag/chunked_file.h:46,
                 from /opt/ros/melodic/include/rosbag/bag.h:41,
                 from /home/dji/catkin_ws/src/r3live/r3live/./src/loam/include/common_lib.h:13,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live.hpp:60,
                 from /home/dji/catkin_ws/src/r3live/r3live/src/r3live_lio.cpp:48:
/usr/include/lz4.h:249:72: note: previous declaration as ‘typedef struct LZ4_streamDecode_t LZ4_streamDecode_t’
 typedef struct { unsigned long long table[LZ4_STREAMDECODESIZE_U64]; } LZ4_streamDecode_t;
                                                                        ^~~~~~~~~~~~~~~~~~
/home/dji/catkin_ws/src/r3live/r3live/src/r3live_vio.cpp: In member function ‘void R3LIVE::load_vio_parameters()’:
/home/dji/catkin_ws/src/r3live/r3live/src/r3live_vio.cpp:441:68: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘std::vector<double, std::allocator<double> >::size_type {aka long unsigned int}’ [-Wformat=]
         printf( "Load camera data size = %d, %d, %d, %d\n", ( int ) camera_intrinsic_data.size(), camera_dist_coeffs_data.size(),
                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 camera_ext_R_data.size(), camera_ext_t_data.size() );
                                                                    ^
/home/dji/catkin_ws/src/r3live/r3live/src/r3live_vio.cpp:441:68: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘std::vector<double, std::allocator<double> >::size_type {aka long unsigned int}’ [-Wformat=]
/home/dji/catkin_ws/src/r3live/r3live/src/r3live_vio.cpp:441:68: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘std::vector<double, std::allocator<double> >::size_type {aka long unsigned int}’ [-Wformat=]
r3live/r3live/CMakeFiles/r3live_mapping.dir/build.make:158: recipe for target 'r3live/r3live/CMakeFiles/r3live_mapping.dir/src/loam/IMU_Processing.cpp.o' failed
make[2]: *** [r3live/r3live/CMakeFiles/r3live_mapping.dir/src/loam/IMU_Processing.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
r3live/r3live/CMakeFiles/r3live_mapping.dir/build.make:62: recipe for target 'r3live/r3live/CMakeFiles/r3live_mapping.dir/src/r3live.cpp.o' failed
make[2]: *** [r3live/r3live/CMakeFiles/r3live_mapping.dir/src/r3live.cpp.o] Error 1
r3live/r3live/CMakeFiles/r3live_mapping.dir/build.make:86: recipe for target 'r3live/r3live/CMakeFiles/r3live_mapping.dir/src/r3live_lio.cpp.o' failed
make[2]: *** [r3live/r3live/CMakeFiles/r3live_mapping.dir/src/r3live_lio.cpp.o] Error 1
r3live/r3live/CMakeFiles/r3live_mapping.dir/build.make:206: recipe for target 'r3live/r3live/CMakeFiles/r3live_mapping.dir/src/r3live_vio.cpp.o' failed
make[2]: *** [r3live/r3live/CMakeFiles/r3live_mapping.dir/src/r3live_vio.cpp.o] Error 1
CMakeFiles/Makefile2:2731: recipe for target 'r3live/r3live/CMakeFiles/r3live_mapping.dir/all' failed
make[1]: *** [r3live/r3live/CMakeFiles/r3live_mapping.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
dji@dji-NUC11PAHi7:~/catkin_ws$ 终端输入：
终端输入：: command not found
dji@dji-NUC11PAHi7:~/catkin_ws$ sudo mv /usr/include/flann/ext/lz4.h /usr/include/flann/ext/lz4.h.bak
dji@dji-NUC11PAHi7:~/catkin_ws$ sudo mv /usr/include/flann/ext/lz4hc.h /usr/include/flann/ext/lz4.h.bak
dji@dji-NUC11PAHi7:~/catkin_ws$  
dji@dji-NUC11PAHi7:~/catkin_ws$ sudo ln -s /usr/include/lz4.h /usr/include/flann/ext/lz4.h
dji@dji-NUC11PAHi7:~/catkin_ws$ sudo ln -s /usr/include/lz4hc.h /usr/include/flann/ext/lz4hc.h
dji@dji-NUC11PAHi7:~/catkin_ws$ catkin_make
Base path: /home/dji/catkin_ws
Source space: /home/dji/catkin_ws/src
Build space: /home/dji/catkin_ws/build
Devel space: /home/dji/catkin_ws/devel
Install space: /home/dji/catkin_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/dji/catkin_ws/build"
####
####
#### Running command: "make -j8 -l8" in "/home/dji/catkin_ws/build"
####
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  4%] Built target test_timer
[  9%] Built target r3live_LiDAR_front_end
[  9%] Built target r3live_generate_messages_py
[  9%] Built target r3live_generate_messages_cpp
[  9%] Built target r3live_generate_messages_lisp
[ 18%] Built target fastlio_mapping
[ 18%] Built target r3live_generate_messages_nodejs
[ 18%] Built target _fast_lio_generate_messages_check_deps_Pose6D
[ 20%] Built target r3live_generate_messages_eus
[ 22%] Building CXX object r3live/r3live/CMakeFiles/r3live_mapping.dir/src/r3live_lio.cpp.o
[ 25%] Building CXX object r3live/r3live/CMakeFiles/r3live_mapping.dir/src/loam/IMU_Processing.cpp.o
[ 27%] Building CXX object r3live/r3live/CMakeFiles/r3live_mapping.dir/src/r3live.cpp.o
[ 29%] Building CXX object r3live/r3live/CMakeFiles/r3live_mapping.dir/src/r3live_vio.cpp.o
[ 34%] Built target fast_lio_generate_messages_cpp
[ 36%] Built target fast_lio_generate_messages_py
[ 40%] Built target fast_lio_generate_messages_eus
[ 77%] Built target r3live_meshing
[ 79%] Built target fast_lio_generate_messages_nodejs
[ 79%] Built target r3live_generate_messages
[ 81%] Built target fast_lio_generate_messages_lisp
[ 81%] Built target fast_lio_generate_messages
/home/dji/catkin_ws/src/r3live/r3live/src/r3live_vio.cpp: In member function ‘void R3LIVE::load_vio_parameters()’:
/home/dji/catkin_ws/src/r3live/r3live/src/r3live_vio.cpp:441:68: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘std::vector<double, std::allocator<double> >::size_type {aka long unsigned int}’ [-Wformat=]
         printf( "Load camera data size = %d, %d, %d, %d\n", ( int ) camera_intrinsic_data.size(), camera_dist_coeffs_data.size(),
                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 camera_ext_R_data.size(), camera_ext_t_data.size() );
                                                                    ^
/home/dji/catkin_ws/src/r3live/r3live/src/r3live_vio.cpp:441:68: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘std::vector<double, std::allocator<double> >::size_type {aka long unsigned int}’ [-Wformat=]
/home/dji/catkin_ws/src/r3live/r3live/src/r3live_vio.cpp:441:68: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘std::vector<double, std::allocator<double> >::size_type {aka long unsigned int}’ [-Wformat=]
[ 84%] Linking CXX executable /home/dji/catkin_ws/devel/lib/r3live/r3live_mapping
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_imgcodecs.so.4.5
[100%] Built target r3live_mapping
dji@dji-NUC11PAHi7:~/catkin_ws$ source ~/catkin_ws/devel/setup.bash

**Comment by ziv-lin** [comment]
see https://github.com/hku-mars/r3live/issues/12
