### ISSUE TITLE
关于设备

### ISSUE THREAD

**Issue by wuming199859** [hku-mars/r3live#28]
您好，林博，请问支持使用zed相机里的内置IMU和RS16雷达来进行复现吗

**Comment by wuming199859** [comment]
这两个设备需要进行外参标定吗

**Comment by ziv-lin** [comment]
1. From the phase of the methodology, R3LIVE is irrelevant to what kind of LiDAR and camera you use. We inspire you to modify our source code for adapting your sensor setups.  
2. The quality of the calibration plays an important role in achieving satisfactory results of R3LIVE, I suggest you kindly calibrate your sensor before you launch our algorithm.
