### ISSUE TITLE
Holes in reconstructed mesh

### ISSUE THREAD

**Issue by aditdoshi333** [hku-mars/r3live#36]
Hello @ziv-lin,

I tried r3live to build large-area meshes. In most cases, it is doing a pretty good job but in some, I got the following problem. 
<img width="472" alt="Screenshot 2022-01-13 at 2 56 21 PM" src="https://user-images.githubusercontent.com/23434856/149303072-38fba5a7-4862-499f-917c-306a0de6dab5.png">
<img width="531" alt="Screenshot 2022-01-13 at 2 56 41 PM" src="https://user-images.githubusercontent.com/23434856/149303096-1c0f7db7-e7b5-447f-af7a-e54a852b7b19.png">
<img width="390" alt="Screenshot 2022-01-13 at 2 56 55 PM" src="https://user-images.githubusercontent.com/23434856/149303100-c6ae932a-044c-4613-bb79-b707439d5363.png">

I am getting such holes all over the surface. It is quite strange as the point is uniform and there are no holes. I am running the default config and launch file. Let me know if I can improve this by any means. 

Thanks

**Comment by aditdoshi333** [comment]
Hello @ziv-lin,

Can you suggest something for this issue?

**Comment by ziv-lin** [comment]
Try to increase the value of close_holes_dist to close such holes?
https://github.com/hku-mars/r3live/blob/b5855c817e7b00b5b933393bfabae71420ca8a00/r3live/launch/r3live_reconstruct_mesh.launch#L29
