### ISSUE TITLE
Is there any way to add a software sync between external imu and Livox lidar?

### ISSUE THREAD

**Issue by Tomato1107** [hku-mars/r3live#38]
In the FAST_LIO, there has a software sync enable between external imu and Livox lidar.
Is that possible in the R3LIVE too?
I tried to add the software sync enable between external imu and Livox lidar.
And lio part has already been worked, but the camera frame almost has no update.
I can not see any camera infomation in the rviz.
Do you have any suggestions?

**Comment by Tomato1107** [comment]
[](url)

**Comment by Tomato1107** [comment]
![issue](https://user-images.githubusercontent.com/19368992/149434269-686d704c-cc1e-45f6-8623-403735fc9970.png)

**Comment by Tomato1107** [comment]
The sync has been solved by changing the time of the lidar to the ros time. The method in the fast_lio is convert the ros time of the external imu to the time of the lidar that starts from 0.

**Comment by farhad-dalirani** [comment]
I have a Velodyne Lidar, I does not have an internal IMU.
What can I do to sync int with LiDAR and also find theri external calibration?
