### ISSUE TITLE
Code release 

### ISSUE THREAD

**Issue by aditdoshi333** [hku-mars/r3live#4]
Hello @ziv-lin ,

Thanks for sharing r3live paper. Currently for a college project I am using r2live but I am not able to generate good map when the environment has limited features. From the example video it looks like r3live is solving this problem. I am eagerly waiting for the code release if possible can you please share the tentative date of the code release. I know you are waiting for the reviewer comment, If possible please share the timelines. 

Thank you

**Comment by ziv-lin** [comment]
Sorry for the late reply, we have just received the reviewer comments in the first round of paper reviews, and we decide to release our codes before Dec 31, 2021.
