### ISSUE TITLE
Is it possible to build this on non intel

### ISSUE THREAD

**Issue by griz1112** [hku-mars/r3live#40]
Will this build on something other than intel hardware?

**Comment by ziv-lin** [comment]
R3LIVE can on those platforms with the SSE instruction set. Besides the Intel hardware, our package can also launch at AMD platform (e.g., see an example in the issue https://github.com/hku-mars/r3live/issues/11).
![image](https://user-images.githubusercontent.com/9316645/152732789-c8a38747-0d00-4c70-bf5a-5fba09b6accc.png)
