### ISSUE TITLE
还是运行测试的时候的那个问题

### ISSUE THREAD

**Issue by BoyLazyA** [hku-mars/r3live#42]
在保证运行opencv和编译opencv版本都是3.4.16后，还是一直会崩掉，运行内存时16G.
![image](https://user-images.githubusercontent.com/51414201/149902427-612dce9d-7866-41ff-ba1e-4abab146784b.png)
![image](https://user-images.githubusercontent.com/51414201/149902466-f6f6cb58-d768-400a-a01c-588946bca841.png)
![image](https://user-images.githubusercontent.com/51414201/149902590-808f6ff0-cbbe-412e-8b98-34c40315af68.png)
还有就是，rqt_image_view命令后也是能看见图片的，这个怎么解决呀？

**Comment by ChunqiuYang** [comment]
I have the same problem. How can we solve it?

**Comment by BoyLazyA** [comment]
> 

sorry, I do not solve it,

**Comment by ToutDonner** [comment]
可以尝试一下拆卸系统自带的opencv3.2.0（我的是melodic），然后将最新版的cvbridge和r3live放在同一个src下进行编译。我的电脑在编译livox_camera_calib时会出现这个错误，我按照上述方法解决的。

**Comment by BoyLazyA** [comment]
> 

照做还是不行，很奇怪。

**Comment by Divenire1998** [comment]
我将Boost的切换到1.65.1后，运行正常了，楼主试试呢。 但是我的Rviz显示还有点问题，不过至少能跑了 hh
