### ISSUE TITLE
rxlive_handheld 

### ISSUE THREAD

**Issue by antun008** [hku-mars/r3live#43]
[rxlive_handheld ](https://github.com/ziv-lin/rxlive_handheld)

Within CAD files of your handheld device could you also add schematic and explanations about connecting different sensors to embed them together? Time Synchronization, hardware (lidar, camera, battery, laptop) and software? You don't have to go into too much detail, but still, a little more detailed than explained in the article. It seems to me that it would help me a lot.

Thank you in advance,
Best regards,
Antun Jakopec

**Comment by ziv-lin** [comment]
The CAD files of our hardware design are now available in [rxlive_handheld](https://github.com/ziv-lin/rxlive_handheld). You can now download, print, edit and assemble our handheld device by following the guides.
![introduction_alpha](https://user-images.githubusercontent.com/9316645/151564507-0080711e-6c88-4fe9-8582-3a9f4a15c987.png)

![Guide_to_ee_connection](https://user-images.githubusercontent.com/9316645/151564451-be9a9f87-b6e3-46b1-b0f2-31e4b6c50886.png)

**Comment by antun008** [comment]
Thanks for the answer!
I would ask your one more thing you if are able to answer: Do you have any tutorial on time synchronization? What software to use, what hardware to synchronize time?

**Comment by ziv-lin** [comment]
Please refer to the past issues https://github.com/hku-mars/r3live/issues/5 and https://github.com/hku-mars/r3live/issues/10.

For the camera sensor, we do not make any hardware synchronization between LiDAR and camera sensor, the time-offset between IMU (LiDAR built-in) is online estimated by our algorithm (both R2LIVE and our new work R3LIVE).
