### ISSUE TITLE
如何提升textured图的效果

### ISSUE THREAD

**Issue by tomchen008** [hku-mars/r3live#47]
![IMG_20220206_024337](https://user-images.githubusercontent.com/1850399/152654800-246a1a43-e0ea-4dd8-bf89-8bc89cc9b6fa.jpg)
点云图的效果很棒，但是textured图的效果不是很好，是不是我的问题？

**Comment by tomchen008** [comment]
配置如下:
![1644087178561410552718388866225](https://user-images.githubusercontent.com/1850399/152654970-6c9133cc-6637-4380-988d-26a1b2be8c80.jpg)

**Comment by ziv-lin** [comment]
Try to increase the value of smooth_mesh_factor to make the mesh smoother?
https://github.com/hku-mars/r3live/blob/cee0e510ff80444d8de4b57fbeb194253ba9d840/r3live/launch/r3live_reconstruct_mesh.launch#L32
