### ISSUE TITLE
LIO VIO单独运行

### ISSUE THREAD

**Issue by Maple-Yang-neu** [hku-mars/r3live#50]
请问林博，R3LIVE可以独立运行VIO和LIO吗？我看R3LIVE使用的VIO系统相比于R2LIVE比较轻量，请问它是怎么达到比R2LIVE更好的精度呢，主要是LIO部分的作用吗？

**Comment by ziv-lin** [comment]
1. The LIO subsystem of R3LIVE and R2LIVE is the same (see [fast-lio](https://github.com/hku-mars/FAST_LIO)).
2. The main improvement of R3LIVE w.r.t. R2LIVE is the way of fusing the camera data. In R2LIVE, the VIO system uses the extracted feature points,  first triangulates visual 3D points, and then further refine them within the local sliding window. In R3LIVE, the VIO substem directly uses the raw input camera data, updates the visual measurement by minimizing the photometric error, which is a more effective and efficient way for fusing visual measurements.
