### ISSUE TITLE
[Issue] Steady inclination along SLAM

### ISSUE THREAD

**Issue by Camilochiang** [hku-mars/r3live#51]
The data was captured 10 seconds after starting the algorithm, giving enough time for IMU calibration as previously recommended.
After post processing the 3D data and fitting a plane to the ground the following array result for the plane equation (ax + by +cz + d = 0):
`array([-0.05517862,  0.09160666,  0.99426533,  1.39617296])`

I do have the small impression that somewhere during the IMU initialization the value of Z get too high, this make all the 3D point cloud to have a slop of around 45° in the Z axis (simplified to 1 dimension).

**Comment by ziv-lin** [comment]
What is your problem?

**Comment by Camilochiang** [comment]
- The view angle is aligned to the Y axis
- The scanned place is known to be flat
- R3live estimate the full pointcloud tilded. When a plane is fitted the slope is almost 1, What i found weird no?

![Screenshot from 2022-02-11 08-19-55](https://user-images.githubusercontent.com/48471579/153551641-650203d7-7278-45a7-8a9a-1760cc758fa3.png)

**Comment by Camilochiang** [comment]
@ziv-lin , May I ask why this issue was closed?
