### ISSUE TITLE
Livox Horizon

### ISSUE THREAD

**Issue by BellosC** [hku-mars/r3live#53]
Hello to all, 

Is this package compatible with Livox Horizon?
Can i use Livox Horizon instead of Livox Avia and have the same results?

Thank you in advance.

**Comment by ziv-lin** [comment]
Of course, you can. Some of the guys have tried our algorithm with the Livox Horizon and found they work well.

**Comment by BellosC** [comment]
Thank you @ziv-lin for your fast reply.
I will close the issue.

**Comment by RalphCodesTheInternet** [comment]
How about the Livox Tele? Can this work good as well?

**Comment by stagsz** [comment]
I've tried but I'm not got it working. I hope there is a solution that I have missed.
