### ISSUE TITLE
model gets slower while generating new points

### ISSUE THREAD

**Issue by mameesie** [hku-mars/r3live#55]
Thanks ziv-lin for this great work! I have a problem with running the larger ROSbag files:
 
At first the points get generated fast. But after the model becomes larger the points get generated slower and slower till it drops to about 1 frame per second. It then becomes hard to move or zoom the model. Then after all points are generated the model becomes very fast again (with zooming and moving around). When i checked the GPU utilization i saw that during generation of new points, the GPU wasn't being utilized and the CPU was doing all the work. after all the points were generated the GPU started to work and the model became very fast again (with zooming and moving around).
 
This happend both on the two systems that i tried (both on ubuntu 20.04):
 
MacBook dual boot:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/97596114/154484379-0b5abc96-ab96-4d45-9bf4-238b8214f919.png">

 
Google cloud (16 threads), + Nvidia p4 gpu:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/97596114/154484435-5b489dfe-abf0-40df-9931-2ebd7aa6c56d.png">

 
Also I have a warning that says reset ImuProces
![image](https://user-images.githubusercontent.com/97596114/154484455-9e4d41cd-c1e8-43e3-a6eb-14abf8b9a7ce.png)

And sometimes, not that often, I get this error:
![image](https://user-images.githubusercontent.com/97596114/154484469-84830eb0-6d57-4729-b547-e6a6a7d05d59.png)
 

Is there maybe a problem with hardware acceleration? Or do I need more CPU for running the larger ROSbag files? Or am I missing something completely? Thanks for your time and effort!

**Comment by mameesie** [comment]
Im still having this problem. I hope someone can help?

**Comment by ziv-lin** [comment]
Yes, I think such a phenomenon is reasonable. When refreshing the point cloud for visualization, Rviz requires consuming the time for updating the buffer for rendering, which makes the refreshing rate low.

**Comment by mameesie** [comment]
thanks for your answer

**Comment by mameesie** [comment]
How would you recommend to increase the frame rate?
