### ISSUE TITLE
您好，我在运行自己的数据时无法显示图像，并且camera frame一直显示为2

### ISSUE THREAD

**Issue by ToutDonner** [hku-mars/r3live#58]
![Screenshot from 2022-02-19 15-29-56](https://user-images.githubusercontent.com/84958138/154792631-27d453e4-3941-4ca8-9d20-c112caa4d580.png)
![Screenshot from 2022-02-19 15-59-03](https://user-images.githubusercontent.com/84958138/154792639-726348a9-5086-43ae-81b4-cf80010a1d36.png)

**Comment by ToutDonner** [comment]
![Screenshot from 2022-02-19 19-27-39](https://user-images.githubusercontent.com/84958138/154800064-6d8bbf2b-b104-4398-9d9d-045dee7a7588.png)
这是我的标定结果

**Comment by ToutDonner** [comment]
这是我标定的外参以及config中的配置
![Screenshot from 2022-02-19 20-10-18](https://user-images.githubusercontent.com/84958138/154800204-6c002e8f-49fb-4888-8818-e51de536b0cc.png)

**Comment by huangsiyuan0717** [comment]
@ToutDonner  你好，请问你是怎么解决的， 我也碰到了这个问题

**Comment by Yangchunqiu** [comment]
这个应该就是camera的数据没接入进去，尝试着在launch file里面把相机的topic改成自己的

**Comment by ToutDonner** [comment]
> 有可能是相机和雷达时间不同步，使用他们修改过后的livox driver 应该是以系统时间为标准的
> 
> > 这个应该就是camera的数据没接入进去，尝试着在launch file里面把相机的topic改成自己的
> 
> 
> 
> 我也出现这个情况 改了自己的话题还是只有两帧(相机用的realsense d455)
> 
>

**Comment by duckbubi29** [comment]
> > 有可能是相机和雷达时间不同步，使用他们修改过后的livox driver 应该是以系统时间为标准的
> > > 这个应该就是camera的数据没接入进去，尝试着在launch file里面把相机的topic改成自己的
> > 
> > 
> > 我也出现这个情况 改了自己的话题还是只有两帧(相机用的realsense d455)

你好，怎么解决时间不同步问题呢

**Comment by FengYuQ** [comment]
请问这个问题解决了嘛

**Comment by ToutDonner** [comment]
解决了，我这里是因为雷达和相机时间没有同步，要使用修改过后的livox driver

**Comment by wanghui-min** [comment]
> 解决了，我这里是因为雷达和相机时间没有同步，要使用修改过后的livox driver

能告知怎么进行同步吗？或者livoxdriver哪里修改？

**Comment by ToutDonner** [comment]
> > 解决了，我这里是因为雷达和相机时间没有同步，要使用修改过后的livox driver
> 
> 
> 
> 能告知怎么进行同步吗？或者livoxdriver哪里修改？

直接使用mars他们修改的那个就可以，在他们github里有

**Comment by Russell-fan** [comment]
请问一下，是需要使用作者修改的那个[livox_ros_driver_for_R2LIVE](https://github.com/ziv-lin/livox_ros_driver_for_R2LIVE)录制包吗？我用的是这个修改过的驱动录制的包，可还是有这个错误。

**Comment by ToutDonner** [comment]
我是这么做的，你可能需要调整一下相机？> 请问一下，是需要使用作者修改的那个[livox_ros_driver_for_R2LIVE](https://github.com/ziv-lin/livox_ros_driver_for_R2LIVE)录制包吗？我用的是这个修改过的驱动录制的包，可还是有这个错误。

**Comment by RuizhiChang** [comment]
> 请问一下，是需要使用作者修改的那个[livox_ros_driver_for_R2LIVE](https://github.com/ziv-lin/livox_ros_driver_for_R2LIVE)录制包吗？我用的是这个修改过的驱动录制的包，可还是有这个错误。

我是这么做的，你可能需要检查一下相机？

**Comment by farhad-dalirani** [comment]
Hello,

I use Realsense, and I have a similar problem. Can you explain how you solved it?

https://github.com/hku-mars/r3live/issues/156#issue-1570393194

**Comment by farhad-dalirani** [comment]
> > Excuse me, do I need to use the [livox_ros_driver_for_R2LIVE](https://github.com/ziv-lin/livox_ros_driver_for_R2LIVE) recording package modified by the author? I use this modified driver recording package, but I still have this error.
> 
> That's what I did, you might want to check the camera?


Hello @ToutDonner ,

I use Realsense, and I have a similar problem. Can you explain how you solved it? Also, I used Velodyne LiDAR. You can see my problem here:

https://github.com/hku-mars/r3live/issues/156#issue-1570393194

**Comment by FengYuQ** [comment]
What's your OpenCV version, I remember when I change the opencv version to 3.14&nbsp; the program was worked.




冯宇祺
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hku-mars/r3live"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 中午11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hku-mars/r3live] 您好，我在运行自己的数据时无法显示图像，并且camera frame一直显示为2 (Issue #58)





   
Excuse me, do I need to use the livox_ros_driver_for_R2LIVE recording package modified by the author? I use this modified driver recording package, but I still have this error.
  
That's what I did, you might want to check the camera?
  
Hello @ToutDonner ,
 
I use Realsense, and I have a similar problem. Can you explain how you solved it?
 
#156 (comment)

**Comment by RuizhiChang** [comment]
> > > Excuse me, do I need to use the [livox_ros_driver_for_R2LIVE](https://github.com/ziv-lin/livox_ros_driver_for_R2LIVE) recording package modified by the author? I use this modified driver recording package, but I still have this error.
> 
> > 
> 
> > That's what I did, you might want to check the camera?
> 
> 
> 
> 
> 
> Hello @ToutDonner ,
> 
> 
> 
> I use Realsense, and I have a similar problem. Can you explain how you solved it? Also, I used Velodyne LiDAR. You can see my problem here:
> 
> 
> 
> https://github.com/hku-mars/r3live/issues/156#issue-1570393194

@farhad-dalirani you can record a piece of data and check the time reference of the camera and the lidar. r3live does not need hard synchronization, but the two sensors need to use the same time reference

**Comment by farhad-dalirani** [comment]
> > > > Excuse me, do I need to use the [livox_ros_driver_for_R2LIVE](https://github.com/ziv-lin/livox_ros_driver_for_R2LIVE) recording package modified by the author? I use this modified driver recording package, but I still have this error.
> > 
> > 
> > > 
> > 
> > 
> > > That's what I did, you might want to check the camera?
> > 
> > 
> > Hello @ToutDonner ,
> > I use Realsense, and I have a similar problem. Can you explain how you solved it? Also, I used Velodyne LiDAR. You can see my problem here:
> > [#156 (comment)](https://github.com/hku-mars/r3live/issues/156#issue-1570393194)
> 
> @farhad-dalirani you can record a piece of data and check the time reference of the camera and the lidar. r3live does not need hard synchronization, but the two sensors need to use the same time reference

@ToutDonner Thank you for the quick reply, I really appreciate it.

What do you mean by the same-time reference? For example, if both camera and Lidar messages have ROS time in their header, does it satisfy your comment?

**Comment by RuizhiChang** [comment]
> > > > > Excuse me, do I need to use the [livox_ros_driver_for_R2LIVE](https://github.com/ziv-lin/livox_ros_driver_for_R2LIVE) recording package modified by the author? I use this modified driver recording package, but I still have this error.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > That's what I did, you might want to check the camera?
> 
> > > 
> 
> > > 
> 
> > > Hello @ToutDonner ,
> 
> > > I use Realsense, and I have a similar problem. Can you explain how you solved it? Also, I used Velodyne LiDAR. You can see my problem here:
> 
> > > [#156 (comment)](https://github.com/hku-mars/r3live/issues/156#issue-1570393194)
> 
> > 
> 
> > @farhad-dalirani you can record a piece of data and check the time reference of the camera and the lidar. r3live does not need hard synchronization, but the two sensors need to use the same time reference
> 
> 
> 
> @ToutDonner Thank you for the quick reply, I really appreciate it.
> 
> 
> 
> What do you mean by the same-time reference? For example, if both camera and Lidar messages have ROS time in their header, does it satisfy your comment?

You can look this pic![image](https://user-images.githubusercontent.com/84958138/216749315-033cf26d-7fb8-4aac-80fb-5e692a811001.png)

**Comment by farhad-dalirani** [comment]
Hi, @ToutDonner and @FengYuQ 

Hi, since I use Velodyne and a camera and message time are marked with ROS, it seems there is no synchronization problem. However, I experience a significant drift. I explained my problem in detail in this issue:

https://github.com/hku-mars/r3live/issues/157

If you look at it, it would be great.
