### ISSUE TITLE
[r3live_LiDAR_front_end-2]

### ISSUE THREAD

**Issue by MOSEAA** [hku-mars/r3live#62]
你好，我遇到了一个很奇怪的问题，我重新装了多遍opencv，依然有这样的问题，请问您可以给我一些建议吗？真的好难搞哟
对了，我的rqt_image_view也可以正常使用。

![2022-02-26 04-15-19屏幕截图](https://user-images.githubusercontent.com/64082545/155793511-0ac9de54-62c0-465e-8920-aa70db4a0c3b.png)

**Comment by MOSEAA** [comment]
![2022-02-26 04-16-24屏幕截图](https://user-images.githubusercontent.com/64082545/155793907-30201e7a-9703-41cc-8365-edaa7c16c5d5.png)

**Comment by MOSEAA** [comment]
![2022-02-26 04-18-07屏幕截图](https://user-images.githubusercontent.com/64082545/155794525-0d1c0710-24bb-423f-a0e9-43b1f190af08.png)

**Comment by zengkailiang** [comment]
> 我找到问题所在了，尝试多次，与环境配置有关，我的环境配置是ubuntu18.04 + gcc7.5 + boost 1.65.1 + eigen 3.3.4 + opencv 3.4.16

我也遇到类似的问题，我的环境是ubuntu18.04 + gcc7.5 + boost 1.65.1 + eigen 3.3.4 + opencv 4.4.0 
================================================================================REQUIRED process [r3live_mapping-3] has died!
process has died [pid 17396, exit code -11, cmd /home/lzk/r3live/devel/lib/r3live/r3live_mapping __name:=r3live_mapping __log:=/home/lzk/.ros/log/b122e9a4-9de4-11ec-9fe8-b42e99818be9/r3live_mapping-3.log].
log file: /home/lzk/.ros/log/b122e9a4-9de4-11ec-9fe8-b42e99818be9/r3live_mapping-3*.log
Initiating shutdown!
================================================================================

你是如何解决的呢

**Comment by zengkailiang** [comment]
> 我找到问题所在了，尝试多次，与环境配置有关，我的环境配置是ubuntu18.04 + gcc7.5 + boost 1.65.1 + eigen 3.3.4 + opencv 3.4.16

我也遇到类似的问题, 我的环境是 ubuntu18.04 + gcc7.5 + boost 1.65.1 + eigen 3.3.4 + opencv
================================================================================REQUIRED process [r3live_mapping-3] has died!
process has died [pid 17396, exit code -11, cmd /home/lzk/r3live/devel/lib/r3live/r3live_mapping __name:=r3live_mapping __log:=/home/lzk/.ros/log/b122e9a4-9de4-11ec-9fe8-b42e99818be9/r3live_mapping-3.log].
log file: /home/lzk/.ros/log/b122e9a4-9de4-11ec-9fe8-b42e99818be9/r3live_mapping-3*.log
Initiating shutdown!
================================================================================
你是怎么解决的呢
