### ISSUE TITLE
How did you record your .bag file?

### ISSUE THREAD

**Issue by BellosC** [hku-mars/r3live#63]
Hello, could you **share the .launch file** that you used in order to get the following .bag file *(hku_campus_seq_00.bag)*?
![Screenshot from 2022-03-02 12-22-14](https://user-images.githubusercontent.com/70270581/156343530-1207f668-768e-4006-8286-4bc4182efef7.png)
*(I am trying to collect my own data but for the moment i am not sure how to do that)*
Thank you in advance.

**Comment by ziv-lin** [comment]
I record the rosbag file with the following command:
```
rosbag record /camera/image_color/compressed /camera/image_color/compressed/parameter_descriptions /camera/image_color/compressed/parameter_updates /livox/imu  /livox/lidar
```
Of course, you can also record all ros messages with:
```
rosbag record -a
```

**Comment by BellosC** [comment]
Hi, 

Thanks for your feedback.

Although my question was not how you record the bag file.

My question was how you triggered the livox and the camera to start recording data simultaneously.

If you could share the launch file for that, it would be extremely helpful.

Thanks again!
