### ISSUE TITLE
show tracked points in image

### ISSUE THREAD

**Issue by zaalsabb** [hku-mars/r3live#67]
Hi, how can we visualize the tracked points on the image similar to this example?
https://github.com/ziv-lin/r3live_dataset/blob/main/gifs/degenerate_00.gif

When I run the example I don't see the tracked points in rviz in the /track_img topic. How do I visualize the tracked points?

Thanks!

**Comment by ziv-lin** [comment]
This part of the debugging code has been removed in this release version. You can visualize the tracked points by plotting the lines among tracked points in the current-frame and last-frame.

**Comment by ly-uuu** [comment]
> Hi, how can we visualize the tracked points on the image similar to this example? https://github.com/ziv-lin/r3live_dataset/blob/main/gifs/degenerate_00.gif
> 
> When I run the example I don't see the tracked points in rviz in the /track_img topic. How do I visualize the tracked points?
> 
> Thanks!
Did you solve it?
