### ISSUE TITLE
livox lidar data type error

### ISSUE THREAD

**Issue by gongyue666** [hku-mars/r3live#68]
Hi, I use my livox-mid70 and realsense d435 to run r3live, the lidar data type is always. when I use sensor_msgs/PointCloud2, it told me should use livox/cutom, and  when I change the type, it told me need sensor_msgs ....error logs is like this:
[ERROR] [1646964020.047520342]: Client [/r3live_LiDAR_front_end] wants topic /livox/lidar to have datatype/md5sum [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6], but our version has [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181]. Dropping connection.

[ERROR] [1646963951.610199012]: Client [/r3live_mapping] wants topic /livox/lidar to have datatype/md5sum [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181], but our version has [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6]. Dropping connection.
---

My system is ubuntu 20.04, livox_driver is from r2live version.
here is config file:
![config](https://user-images.githubusercontent.com/15926228/157788656-e779a92c-acab-4b9d-a8aa-cd4e94e821fc.png)
and here is launch  file:
![r3launch](https://user-images.githubusercontent.com/15926228/157788663-6cf8334e-e7bb-4b44-a536-c7c6bed52997.png)

**Comment by Camilochiang** [comment]
Well, basically is what is saying. You are using the wrong LiDAR message type. Did you pre recorded the rosbag?

also, if you are using mid70 you can change the parameter lidar_front_end / scans from 6 to 1 has mid70 have only one line at diferente of avia

**Comment by ziv-lin** [comment]
Yes, I agree with @Camilochiang, I guess you are using the wrong LiDAR message type. Are your using the PCL_pointcloud2? the right one is livox_custom_message (see our example).

**Comment by gongyue666** [comment]
![Screenshot from 2022-03-14 09-49-04](https://user-images.githubusercontent.com/15926228/158091471-5fa6a424-eaab-433f-a2d5-b5660cafd752.png)
acturelly I use the message type as livox_ros_driver/CustomMsg, but it also get this error. No matter I use "livox_ros_driver/CustomMsg" or "sensor_msgs/PointCloud2" I will get the error that need the other message the type. Another error  log:
![Screenshot from 2022-03-14 09-56-51](https://user-images.githubusercontent.com/15926228/158091851-81319c03-7ff4-4ae7-b591-4ac4a8600111.png)

**Comment by gongyue666** [comment]
Do the node  "r3live_mapping" and node "r3live_Lidar_front_end" need different data type?

**Comment by ruiche01** [comment]
@gongyue666 Do you solve this problem? I also meet this problem

**Comment by gongyue666** [comment]
check the launch file, the lidar data type is different in the two nodes

**Comment by linzs-online** [comment]
I've met the same problem , couold you tell me how you fixed this problem? @gongyue666 specifically where you changed the param .thanks.

**Comment by gongyue666** [comment]
do not change the lidar topic in launch file

**Comment by jiatianluo** [comment]
请问您解决这个问题了吗，我也遇到了同样问题

**Comment by peter-ivarsen** [comment]
If you have a bag with lidar messages on the sensor_msgs/PointCloud2 format, you could set lidar_type: 0 in r3live_config.yaml.
This will activate the MID40 lidar type in LiDAR_front_end.cpp wich uses ha handler that handles sensor_msgs/PointCloud2
