### ISSUE TITLE
Question about the function R3LIVE::lasermap_fov_segment()

### ISSUE THREAD

**Issue by Minzhao1995** [hku-mars/r3live#73]
您好，

我对lasermap_fov_segment()函数的功能不太明白。尽管现在cube_side_length设的很大，但还是想问一下函数的作用。

我的理解是featsArray起到localmap的作用。在FASTLIO里，范围外的box会从ikdtree删掉，但是R3LIVE这里好像并没有从ikdtree删掉？因此featsArray也没有起到作用？

（p.s. 好像J、K方向上featsArray的移位有bug？for循环里用的是i，会进死循环）

谢谢！

**Comment by zhangshuoneu** [comment]
我也觉得，lasermap_fov_segment()函数因为cube_length设置的很大，不需要使用到，但实际写的有问题，r3live代码简洁性和合理性还需要改进，fast_lio2就很棒了
