### ISSUE TITLE
camera-frame just capture 2 frame

### ISSUE THREAD

**Issue by huangsiyuan0717** [hku-mars/r3live#75]
Thanks for your great job!
I try to run my onw data, but just can capture 2 camera frame, what can I do?
My environment as the following:(hardware: livox-horizon, realsense D455
![10](https://user-images.githubusercontent.com/69231540/160629947-91a3113e-f14d-4965-a6f7-2dea44cfcc78.png)
![11](https://user-images.githubusercontent.com/69231540/160629958-8b1fff7f-707e-4eaa-9ac4-ea9f1c324fbd.png)
![12](https://user-images.githubusercontent.com/69231540/160629963-8dc4aa93-4ff8-45e8-8224-e8972e436deb.png)
And I changed the configure 
``` <param name="Image_topic" type="string" value= "/camera/color/image_raw" /> ```
Also there are other param changed in r3live.yaml.
Maybe the same as https://github.com/hku-mars/r3live/issues/58#issue-1144605301

**Comment by zengkailiang** [comment]
image和lidar时间戳不同步导致的吧

**Comment by duckbubi29** [comment]
> Thanks for your great job! I try to run my onw data, but just can capture 2 camera frame, what can I do? My environment as the following:(hardware: livox-horizon, realsense D455 ![10](https://user-images.githubusercontent.com/69231540/160629947-91a3113e-f14d-4965-a6f7-2dea44cfcc78.png) ![11](https://user-images.githubusercontent.com/69231540/160629958-8b1fff7f-707e-4eaa-9ac4-ea9f1c324fbd.png) ![12](https://user-images.githubusercontent.com/69231540/160629963-8dc4aa93-4ff8-45e8-8224-e8972e436deb.png) And I changed the configure `<param name="Image_topic" type="string" value= "/camera/color/image_raw" />` Also there are other param changed in r3live.yaml. Maybe the same as [#58 (comment)](https://github.com/hku-mars/r3live/issues/58#issue-1144605301)

你好，我也遇到了相同的问题，请问你解决了吗

**Comment by farhad-dalirani** [comment]
@huangsiyuan0717 @zengkailiang Did you solve the problem? I use velodyne-16 and a realsense.
