### ISSUE TITLE
运行R3live时出现Control panel卡死

### ISSUE THREAD

**Issue by Prophet-w** [hku-mars/r3live#77]
我的Opencv编译、运行版本都是3.4.16，编译通过，跑数据包时就会出现control panel卡死，强制关闭control panel后程序就崩。然后我将最新版的cvbridge和r3live放在同一个src下进行编译，结果还是这个问题，有大佬知道是哪里出现问题了吗？谢谢大佬能指点一下
![2022-04-06 00-02-55 的屏幕截图](https://user-images.githubusercontent.com/41831012/161800001-0ec69836-40bd-4678-a4fe-92bf322b3ef2.png)
。

**Comment by wing2791** [comment]
报错信息：`XDG RUNTIME DIR (runuser/1000) is not owned by us (uid 0), but by uid1000! (This could e.g. happen if you try to connect to a non-root PulseAudioas a root user, over the native protocol. Don't do that.)`
在**普通用户权限**下运行`roslaunch r3live r3live_bag.launch`命令
然后开一个新终端运行`rosbag play YOUR_DOWNLOADED.bag`命令，不要求是否为普通用户
