### ISSUE TITLE
[r3live_meshing-1]:process has died

### ISSUE THREAD

**Issue by ionia1999** [hku-mars/r3live#85]
您好，在运行r3live_reconstruct_mesh.launch的时候，出现了这样的问题：[r3live_meshing-1]:process has died。您知道该如何解决吗？
![processhasdied](https://user-images.githubusercontent.com/73088623/165486662-b9102846-c9c1-4322-b535-0790b53f2609.png)

**Comment by laoyu-wq** [comment]
您好，请问您解决这个问题了吗
