### ISSUE TITLE
FLIR Driver

### ISSUE THREAD

**Issue by ccq0905** [hku-mars/r3live#86]
I want to know where is the driver of the FLIR BFS camera!
Because now the driver I'm using doesn't provide the message:
/camera/image_color/compressed
which result the bag recording datas very large.
So could you help me?

**Comment by Camilochiang** [comment]
https://github.com/ros-drivers/flir_camera_driver

**Comment by ccq0905** [comment]
It's useful for it. But I still can't find the topic called /camera/image_color/compressed。
Does the author write the driver himself, or can I reduce memory when the algorithm effect is not affected?
