### ISSUE TITLE
No points in finnal map

### ISSUE THREAD

**Issue by nicetryzz** [hku-mars/r3live#87]
I try to run R3live on our own data. The intrinsic and the extrinsic are already changed in yaml.
But it still doesn't have any points in map.
Can you give some help.
![command](https://user-images.githubusercontent.com/70940473/167393092-c08ea077-c16a-4d88-941d-65588eb62e97.jpg)
![rviz](https://user-images.githubusercontent.com/70940473/167393189-c95cddad-71cb-4d65-a63d-21acb6fe459b.jpg)

**Comment by nicetryzz** [comment]
The extrinsic need transpose!

**Comment by trebladev** [comment]
hi nicetryzz
when i run r3live on my data, i meet same problem with you ,can you tell me how to solver it?
thanks
