### ISSUE TITLE
R3live used too much memory when played my bag

### ISSUE THREAD

**Issue by kktFox** [hku-mars/r3live#89]
Hi, I use my data to run r3live, but the memory used grown quickly. Finally, memory was used up and r3live crashed while bag didn't pass 1/3.
There are 24503 lidar msgs, 36755 camera msgs and 122503 imu msgs in data. Computer Memory is 16GB. Do you have any idea about problem?

**Comment by chenxinyuzdshuai** [comment]
录制压缩图像数据试试

**Comment by lugendary** [comment]
I have the same problem. I want to know if there is a solution to this problem later
