### ISSUE TITLE
Frame-to-map Visual-Inertial odometry

### ISSUE THREAD

**Issue by dongfangzhou1108** [hku-mars/r3live#9]
您好，感谢您开源论文和代码。
关于VIO光度误差update部分，我对于数据关联有些疑问，论文中，是将视觉地图点，通过kdtree找到已经渲染颜色的激光地图点，并构建光度残差吗？那么这么做的话，误差项却并没有包含几何误差。
谢谢！

**Comment by ziv-lin** [comment]
是的，如论文所阐述的我们LIO系统构建负责地图的几何结构(geometry structure), VIO子系统负责更新和渲染地图的纹理(texture), VIO不会改变任何地图的geometry structure (即地图3D点的位置)。
