### ISSUE TITLE
您好，我这边测试r3live的r3live_reconstruct_mesh.launch时程序会挂掉，不知道您有没有遇到过这种情况？

### ISSUE THREAD

**Issue by dandelion-chu** [hku-mars/r3live#90]
我的环境如下图所示，opencv使用版本是4.5.3，ubuntu18.04 melodic，运行roslaunch r3live r3live_bag.launch正常，并且使用hkust_campus_seq_00.bag成功跑出来了建图且保存为pcd文件了；但是测试roslaunch r3live r3live_reconstruct_mesh.launch时，出现问题，程序加载完test.r3live之后就挂掉了，不知道是怎么回事，谢谢哈~~

![微信图片_20220513144534](https://user-images.githubusercontent.com/105104235/168226644-e571a8b0-7e87-431f-b67f-84d951b71a37.jpg)
![微信图片_20220513144542](https://user-images.githubusercontent.com/105104235/168226651-9ba25564-3070-4e35-acf6-3f114ec2b245.jpg)

**Comment by nicetryzz** [comment]
memory太小了

**Comment by dandelion-chu** [comment]
> 

好的，我目前是配置了8G内存和8G SWAP，后面升级下硬件再试试，谢谢哈~~~

**Comment by dandelion-chu** [comment]
> memory太小了

好的，我目前的配置是8G RAM+8G SWAP，后面升级下硬件再重新试一下

**Comment by dandelion-chu** [comment]
> memory太小了

您好，我现在升级设备重新测试，mesh程序还是会挂掉，请问能帮忙排查下是什么问题嘛？我的内存是16G，SWAP是8GB，谢谢哈~~
![微信图片_20220531134811](https://user-images.githubusercontent.com/105104235/171102062-8224e32a-ee07-493a-a708-206fd8a9e250.jpg)
![微信图片_20220531134820](https://user-images.githubusercontent.com/105104235/171102080-8b557704-ed9a-44d0-b0d3-8c78c8f53068.jpg)
![微信图片_20220531134827](https://user-images.githubusercontent.com/105104235/171102098-88c2ff13-4928-4d1d-b0de-70c17d9192fd.jpg)

**Comment by abnerlam** [comment]
@dandelion-chu 请问您解决了吗？
