### ISSUE TITLE
trajectory file

### ISSUE THREAD

**Issue by ly-uuu** [hku-mars/r3live#91]
How does the trajectory file output? I want to evaluate the positioning accuracy.
您好，轨迹文件是怎么输出的呢？想做定位精度的评估

**Comment by Clarence-Feng** [comment]
您好，请问是否解决了轨迹文件的输出问题呢？是否可以分享一下，谢谢

**Comment by ChuqiaoFeng** [comment]
> 



> How does the trajectory file output? I want to evaluate the positioning accuracy. 您好，轨迹文件是怎么输出的呢？想做定位精度的评估

您好，请问是否解决了轨迹文件的输出问题呢？是否可以分享一下，谢谢

**Comment by garriton** [comment]
> > 
> 
> > How does the trajectory file output? I want to evaluate the positioning accuracy. 您好，轨迹文件是怎么输出的呢？想做定位精度的评估
> 
> 您好，请问是否解决了轨迹文件的输出问题呢？是否可以分享一下，谢谢

同问，请问解决了吗，感激！

**Comment by ly-uuu** [comment]
没有解决唉




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月22日(星期四) 晚上8:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [hku-mars/r3live] trajectory file (Issue #91)





     
How does the trajectory file output? I want to evaluate the positioning accuracy. 您好，轨迹文件是怎么输出的呢？想做定位精度的评估
  
您好，请问是否解决了轨迹文件的输出问题呢？是否可以分享一下，谢谢
  
同问，请问解决了吗，感激！
