### ISSUE TITLE
Mesh Reconstruction with PCD only.

### ISSUE THREAD

**Issue by rahulsharma11** [hku-mars/r3live#98]
Hi @ziv-lin ,
Is it possible to use .PCD file and extract the points and provide it in "ReconstructMesh" API?.
I tired to bypass the RGB points (basically camera) and provided the same.
I am getting some output till "delaunay.number_of_vertices", but after graph-cut , i am getting m_mesh faces/vertices=0.
Are these points are tightly coupled with RGB points? 

Thanks.

**Comment by rahulsharma11** [comment]
Hi any update?

**Comment by yahyahajla** [comment]
hello Mr. rahulsharma11, did you find a solution please ?
